// <auto-generated />
using System;
using Hali.Domain.Enums;
using Hali.Infrastructure.Data.Advisories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hali.Infrastructure.Data.Advisories.Migrations
{
    [DbContext(typeof(AdvisoriesDbContext))]
    partial class AdvisoriesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "civic_category", new[] { "electricity", "environment", "governance", "infrastructure", "roads", "safety", "transport", "water" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "civic_category", "civic_category", new[] { "roads", "water", "electricity", "transport", "safety", "environment", "governance", "infrastructure" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "official_post_type", new[] { "advisory_public_notice", "live_update", "scheduled_disruption" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "official_post_type", "official_post_type", new[] { "live_update", "scheduled_disruption", "advisory_public_notice" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hali.Domain.Entities.Advisories.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("JurisdictionLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("jurisdiction_label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("institutions", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Advisories.InstitutionJurisdiction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorridorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("corridor_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("geom");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<Guid?>("LocalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("locality_id");

                    b.HasKey("Id");

                    b.ToTable("institution_jurisdictions", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Advisories.OfficialPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_account_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<CivicCategory>("Category")
                        .HasColumnType("civic_category")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<bool>("IsRestorationClaim")
                        .HasColumnType("boolean")
                        .HasColumnName("is_restoration_claim");

                    b.Property<Guid?>("RelatedClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_cluster_id");

                    b.Property<string>("ResponseStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("response_status");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<OfficialPostType>("Type")
                        .HasColumnType("official_post_type")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("official_posts", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Advisories.OfficialPostScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorridorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("corridor_name");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("geom");

                    b.Property<Guid?>("LocalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("locality_id");

                    b.Property<Guid>("OfficialPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("official_post_id");

                    b.HasKey("Id");

                    b.ToTable("official_post_scopes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
