// <auto-generated />
using System;
using Hali.Infrastructure.Data.Feedback;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hali.Infrastructure.Data.Feedback.Migrations
{
    [DbContext(typeof(FeedbackDbContext))]
    [Migration("20260408100124_AddAppFeedbackTable")]
    partial class AddAppFeedbackTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hali.Domain.Entities.Feedback.AppFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("app_version");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("platform");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rating");

                    b.Property<string>("Screen")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("screen");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Text")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("Rating")
                        .HasDatabaseName("ix_app_feedback_rating");

                    b.HasIndex("Screen")
                        .HasDatabaseName("ix_app_feedback_screen");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("ix_app_feedback_submitted_at");

                    b.ToTable("app_feedback", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
