// <auto-generated />
using System;
using Hali.Infrastructure.Data.Clusters;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hali.Infrastructure.Data.Clusters.Migrations
{
    [DbContext(typeof(ClustersDbContext))]
    partial class ClustersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "civic_category", "civic_category", new[] { "roads", "water", "electricity", "transport", "safety", "environment", "governance", "infrastructure" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "signal_state", "signal_state", new[] { "unconfirmed", "active", "possible_restoration", "resolved", "expired", "suppressed" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hali.Domain.Entities.Clusters.CivisDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision_type");

                    b.Property<string>("Metrics")
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<string>("ReasonCodes")
                        .HasColumnType("jsonb")
                        .HasColumnName("reason_codes");

                    b.HasKey("Id");

                    b.ToTable("civis_decisions", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Clusters.ClusterEventLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<string>("LinkReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("link_reason");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<Guid>("SignalEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("signal_event_id");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "SignalEventId")
                        .IsUnique()
                        .HasDatabaseName("uq_cluster_event_link");

                    b.ToTable("cluster_event_links", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Clusters.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_events_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_events", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Clusters.SignalCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<int>("AffectedCount")
                        .HasColumnType("integer")
                        .HasColumnName("affected_count");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<Point>("Centroid")
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("centroid");

                    b.Property<decimal?>("CivisScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("civis_score");

                    b.Property<string>("DominantConditionSlug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("dominant_condition_slug");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid?>("LocalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("locality_id");

                    b.Property<Guid?>("LocationLabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_label_id");

                    b.Property<string>("LocationLabelText")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("location_label_text");

                    b.Property<int?>("Macf")
                        .HasColumnType("integer")
                        .HasColumnName("macf");

                    b.Property<int>("ObservingCount")
                        .HasColumnType("integer")
                        .HasColumnName("observing_count");

                    b.Property<DateTime?>("PossibleRestorationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("possible_restoration_at");

                    b.Property<int>("RawConfirmationCount")
                        .HasColumnType("integer")
                        .HasColumnName("raw_confirmation_count");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<decimal?>("Sds")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("sds");

                    b.Property<string>("SpatialCellId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("spatial_cell_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("SubcategorySlug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("subcategory_slug");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("TemporalType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("temporal_type");

                    b.Property<string>("Title")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<decimal?>("Wrab")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("wrab");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt")
                        .IsDescending()
                        .HasDatabaseName("ix_signal_clusters_last_seen");

                    b.HasIndex("SpatialCellId", "Category")
                        .HasDatabaseName("ix_signal_clusters_spatial_cell_category");

                    b.HasIndex("State", "LocalityId", "Category")
                        .HasDatabaseName("ix_signal_clusters_state_locality_category");

                    b.ToTable("signal_clusters", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
