// <auto-generated />
using System;
using Hali.Infrastructure.Data.Signals;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hali.Infrastructure.Data.Signals.Migrations
{
    [DbContext(typeof(SignalsDbContext))]
    partial class SignalsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "civic_category", "civic_category", new[] { "roads", "water", "electricity", "transport", "safety", "environment", "governance", "infrastructure" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "location_precision_type", "location_precision_type", new[] { "area", "road", "junction", "landmark", "facility", "pin", "road_landmark" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hali.Domain.Entities.Clusters.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("schema_version");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id");

                    b.ToTable("outbox_events", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Signals.Locality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city_name");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("county_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<MultiPolygon>("Geom")
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("geom");

                    b.Property<string>("WardCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ward_code");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ward_name");

                    b.HasKey("Id");

                    b.ToTable("localities", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Signals.LocationLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AreaName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("area_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FacilityName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("facility_name");

                    b.Property<Point>("Geom")
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("geom");

                    b.Property<string>("JunctionDescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("junction_description");

                    b.Property<string>("LandmarkName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("landmark_name");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<Guid?>("LocalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("locality_id");

                    b.Property<string>("LocationLabelText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("location_label");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("PrecisionType")
                        .HasColumnType("integer")
                        .HasColumnName("precision_type");

                    b.Property<string>("RoadName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("road_name");

                    b.HasKey("Id");

                    b.ToTable("location_labels", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Signals.SignalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("CivisPrecheck")
                        .HasColumnType("jsonb")
                        .HasColumnName("civis_precheck");

                    b.Property<decimal?>("ConditionConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("condition_confidence");

                    b.Property<string>("ConditionSlug")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("condition_slug");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("FreeText")
                        .HasColumnType("text")
                        .HasColumnName("free_text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<Guid?>("LocalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("locality_id");

                    b.Property<decimal?>("LocationConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("location_confidence");

                    b.Property<Guid?>("LocationLabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_label_id");

                    b.Property<string>("LocationSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("location_source");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("NeutralSummary")
                        .HasColumnType("text")
                        .HasColumnName("neutral_summary");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("SourceChannel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_channel");

                    b.Property<string>("SourceLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("source_language");

                    b.Property<string>("SpatialCellId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("spatial_cell_id");

                    b.Property<string>("SubcategorySlug")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("subcategory_slug");

                    b.Property<string>("TemporalType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("temporal_type");

                    b.HasKey("Id");

                    b.HasIndex("SpatialCellId", "OccurredAt")
                        .HasDatabaseName("ix_signal_events_spatial_cell_time");

                    b.HasIndex("LocalityId", "Category", "OccurredAt")
                        .HasDatabaseName("ix_signal_events_locality_category_time");

                    b.ToTable("signal_events", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Signals.TaxonomyCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("SubcategorySlug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("subcategory_slug");

                    b.HasKey("Id");

                    b.HasIndex("Category", "SubcategorySlug")
                        .IsUnique()
                        .HasDatabaseName("uq_taxonomy_category_slug");

                    b.ToTable("taxonomy_categories", (string)null);
                });

            modelBuilder.Entity("Hali.Domain.Entities.Signals.TaxonomyCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("ConditionSlug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("condition_slug");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_positive");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id");

                    b.HasIndex("Category", "ConditionSlug")
                        .IsUnique()
                        .HasDatabaseName("uq_taxonomy_condition_slug");

                    b.ToTable("taxonomy_conditions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
