// <auto-generated />
using System;
using Hali.Domain.Enums;
using Hali.Infrastructure.Data.Participation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hali.Infrastructure.Data.Participation.Migrations
{
    [DbContext(typeof(ParticipationDbContext))]
    [Migration("20260405104010_UseNativeEnumForParticipationType")]
    partial class UseNativeEnumForParticipationType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "participation_type", new[] { "affected", "no_longer_affected", "observing", "restoration_no", "restoration_unsure", "restoration_yes" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "participation_type", "participation_type", new[] { "affected", "observing", "no_longer_affected", "restoration_yes", "restoration_no", "restoration_unsure" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hali.Domain.Entities.Participation.Participation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<string>("ContextText")
                        .HasColumnType("text")
                        .HasColumnName("context_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<ParticipationType>("ParticipationType")
                        .HasColumnType("participation_type")
                        .HasColumnName("participation_type");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "DeviceId", "ParticipationType", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_participation_idempotency");

                    b.ToTable("participations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
